name: Build APK

on:
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: AstroBinge/stargaze-src
          token: ${{ secrets.PAT }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11'

      - name: Install dependencies
        run: flutter pub get

      - name: Display project version
        id: version
        run: echo ::set-output name=version::$(grep version pubspec.yaml | awk '{print $2}' | cut -d '+' -f1)
        shell: bash

      - name: Testing the version
        run: echo ${{ steps.version.outputs.version }}

      - name: Build APK
        run: flutter build apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: StarGAZE v${{ steps.version.outputs.version }}
          body: |
            Release ${{ github.run_id }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload APK
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: stagaze-v${{ steps.version.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
